import { domainMessage } from "../i18n/messages";
import { nextMonday } from "./schedule";
import type { FarmState } from "./types";

export function createDemoState(): FarmState {
  const farmId = "murat-farm";
  return {
    version: 2,
    revision: 0,
    farm: {
      id: farmId,
      name: "Murat’ın Çiftliği",
      ownerId: "murat",
      demoUserId: "murat",
    },
    fields: [
      {
        id: "north",
        farmId,
        name: "Kuzey",
        area: 30,
        crop: domainMessage("cropWheat"),
        stage: "Planned",
        presentation: { iconKey: "field", visualState: "wheat" },
      },
      {
        id: "south",
        farmId,
        name: "Güney",
        area: 35,
        crop: domainMessage("cropCorn"),
        stage: "Growing",
        presentation: { iconKey: "field", visualState: "corn" },
      },
      {
        id: "east",
        farmId,
        name: "Doğu",
        area: 25,
        crop: domainMessage("cropBarley"),
        stage: "Planned",
        presentation: { iconKey: "field", visualState: "barley" },
      },
    ],
    people: [
      {
        id: "murat",
        farmId,
        name: "Murat Demir",
        role: domainMessage("farmOwner"),
        initials: "MD",
        presentation: { visualState: "green", iconKey: "person" },
      },
      {
        id: "ali",
        farmId,
        name: "Ali Kaya",
        role: domainMessage("roleWorker"),
        initials: "AK",
        availability: "available",
        presentation: { visualState: "yellow", iconKey: "person" },
      },
      {
        id: "ece",
        farmId,
        name: "Ece Demir",
        role: domainMessage("roleInventory"),
        initials: "ED",
        presentation: { visualState: "pink", iconKey: "person" },
      },
    ],
    storageLocations: [
      {
        id: "main",
        farmId,
        name: domainMessage("mainWarehouse"),
        description: domainMessage("mainWarehouseDescription"),
        personId: "ece",
        presentation: { iconKey: "warehouse" },
      },
      {
        id: "maintenance",
        farmId,
        name: domainMessage("maintenanceWarehouse"),
        description: domainMessage("maintenanceWarehouseDescription"),
        personId: "murat",
        presentation: { iconKey: "warehouse" },
      },
    ],
    products: [
      {
        id: "product-fertilizer-a",
        farmId,
        name: "Demo Gübre A",
        kind: "fertilizer",
        unit: "kg",
        documentSourceIds: [],
      },
    ],
    inventoryBalances: [
      {
        id: "fertilizer-a",
        farmId,
        productId: "product-fertilizer-a",
        storageLocationId: "main",
        quantity: 800,
      },
    ],
    assets: [
      {
        id: "tractor",
        farmId,
        name: domainMessage("redTractor"),
        kind: "tractor",
        note: domainMessage("machineTractorNote"),
        availability: "available",
        repairExpectedAt: null,
        presentation: { iconKey: "tractor" },
      },
      {
        id: "spreader",
        farmId,
        name: domainMessage("fertilizerSpreader"),
        kind: "spreader",
        note: domainMessage("machineSpreaderNote"),
        availability: "available",
        presentation: { iconKey: "spreader" },
      },
      {
        id: "seeder",
        farmId,
        name: domainMessage("seedDrill"),
        kind: "seeder",
        note: domainMessage("machineSeederNote"),
        availability: "available",
        presentation: { iconKey: "seeder" },
      },
      {
        id: "trailer",
        farmId,
        name: domainMessage("trailer"),
        kind: "trailer",
        note: domainMessage("machineTrailerNote"),
        availability: "available",
        presentation: { iconKey: "trailer" },
      },
    ],
    tasks: [
      {
        id: "north-fertilize",
        farmId,
        title: domainMessage("northFertilize"),
        fieldId: "north",
        personId: "ali",
        assetIds: ["tractor", "spreader"],
        inventoryBalanceId: "fertilizer-a",
        productId: "product-fertilizer-a",
        plannedQuantity: 600,
        type: "fertilizing",
        status: "planned",
        dependencyId: null,
        schedule: { date: null, startTime: null, endTime: null },
        scheduleLabel: "Today",
        completedAt: null,
      },
      {
        id: "east-fertilize",
        farmId,
        title: domainMessage("eastFertilize"),
        fieldId: "east",
        personId: "ali",
        assetIds: ["tractor", "spreader"],
        inventoryBalanceId: "fertilizer-a",
        productId: "product-fertilizer-a",
        plannedQuantity: 300,
        type: "fertilizing",
        status: "planned",
        dependencyId: null,
        schedule: { date: nextMonday(), startTime: "09:00", endTime: "11:00" },
        scheduleLabel: nextMonday(),
        completedAt: null,
      },
      {
        id: "north-sow",
        farmId,
        title: domainMessage("northSow"),
        fieldId: "north",
        personId: "ali",
        assetIds: ["tractor", "seeder"],
        inventoryBalanceId: null,
        productId: null,
        plannedQuantity: null,
        type: "sowing",
        status: "planned",
        dependencyId: "north-fertilize",
        schedule: { date: null, startTime: null, endTime: null },
        scheduleLabel: domainMessage("afterFertilizing"),
        completedAt: null,
      },
    ],
    inventoryTransactions: [],
    operationRecords: [],
    activityLog: [],
    documentSources: [],
    serviceOffers: [
      {
        id: "service-a",
        farmId,
        taskId: "north-fertilize",
        name: "Demo Hizmet A",
        price: 1800,
        transportCost: 200,
        durationHours: 2,
        currency: "TRY",
      },
      {
        id: "service-b",
        farmId,
        taskId: "north-fertilize",
        name: "Demo Hizmet B",
        price: 1500,
        transportCost: null,
        durationHours: null,
        currency: "TRY",
      },
    ],
  };
}
