import { createId } from "../domain/id";
import { isActionDraft } from "../domain/actions";
import type { ActionDraft, FarmState } from "../domain/types";
import { operationSchema } from "./schema";
import type { OperationInterpretation } from "./schema";
import { normalize, verifiedBagKg } from "./documents";
import type { DocumentSection } from "./documents";

// Pure adapter: no repository, browser storage, confirmation or impact calculation.
// IDs and completion IDs are generated by the application, never by the model.
export function adaptActionDraft(
  state: FarmState,
  interpretation: OperationInterpretation,
  sections?: DocumentSection[],
  inputText?: string,
): {
  draft: ActionDraft;
  questions: string[];
  bagConversion: {
    count: number;
    kg: number;
    sourceId: string;
    sectionId: string;
  } | null;
} {
  const value = operationSchema.parse(interpretation);
  const refs = value.targetEntityIds;
  const pairs = [
    [refs.taskId, state.tasks],
    [refs.fieldId, state.fields],
    [refs.productId, state.products],
    [refs.inventoryBalanceId, state.inventoryBalances],
    [refs.assetId, state.assets],
    [refs.personId, state.people],
  ] as const;
  if (
    pairs.some(
      ([id, records]) =>
        id !== null &&
        !records.some((r) => r.id === id && r.farmId === state.farm.id),
    )
  )
    throw new Error("Invalid AI reference");
  const task = state.tasks.find((t) => t.id === refs.taskId);
  if (task && refs.personId && task.personId !== refs.personId)
    throw new Error(
      "Person does not match task; choose the task assignment first",
    );
  const base = {
    id: createId(),
    farmId: state.farm.id,
    actorId: state.farm.demoUserId,
  };
  const questions = [...value.missingFields, ...value.ambiguities];
  const fields = value.extractedFields;
  // Do not let the model silently convert bags or invent precise morning hours.
  if (inputText) {
    const text = normalize(inputText);
    const bags = text.match(/(\d+(?:[.,]\d+)?)\s*(?:cuval|bags?)/);
    const kilograms = text.match(/(\d+(?:[.,]\d+)?)\s*(?:kg|kilo(?:gram)?s?)/);
    if (
      value.intentType === "recordConsumption" &&
      !bags &&
      (!kilograms ||
        fields.unit !== "kg" ||
        fields.quantity !== Number(kilograms[1].replace(",", ".")))
    ) {
      fields.quantity = null;
      questions.push("actualQuantity");
    }
    if (
      bags &&
      value.intentType === "recordConsumption" &&
      (fields.unit !== "bag" ||
        fields.quantity !== Number(bags[1].replace(",", ".")))
    ) {
      fields.quantity = null;
      fields.unit = "bag";
      questions.push("quantityUnit");
    }
    if (
      value.intentType === "rescheduleTask" &&
      !/\d{1,2}[:.]\d{2}/.test(text)
    ) {
      fields.startTime = null;
      fields.endTime = null;
      questions.push("startTime", "endTime");
    }
  }
  let bagConversion = null;
  let draft: ActionDraft;
  if (value.intentType === "recordConsumption") {
    let actualQuantity = fields.quantity;
    if (fields.unit === "bag" && actualQuantity !== null) {
      const kg = verifiedBagKg(refs.productId, sections);
      if (kg === null) {
        actualQuantity = null;
        questions.push("bagSize");
      } else {
        bagConversion = {
          count: actualQuantity,
          kg,
          sourceId: "doc-fertilizer-a",
          sectionId: "packaging",
        };
        actualQuantity = Math.round(actualQuantity * kg * 1000) / 1000;
      }
    } else if (fields.unit !== "kg") {
      actualQuantity = null;
      questions.push("quantityUnit");
    }
    draft = {
      ...base,
      kind: "recordConsumption",
      completionId: `completion-${refs.taskId ?? base.id}`,
      taskId: refs.taskId,
      fieldId: refs.fieldId,
      productId: refs.productId,
      inventoryBalanceId: refs.inventoryBalanceId,
      actualQuantity,
    };
  } else if (value.intentType === "setAssetAvailability") {
    draft = {
      ...base,
      kind: "setAssetAvailability",
      assetId: refs.assetId,
      availability: fields.availability ?? "unknown",
    };
    if (!fields.availability) questions.push("availability");
  } else {
    draft = {
      ...base,
      kind: "rescheduleTask",
      taskId: refs.taskId,
      schedule: {
        date: fields.date,
        startTime: fields.startTime,
        endTime: fields.endTime,
      },
    };
  }
  if (!isActionDraft(draft)) throw new Error("Invalid AI draft");
  return { draft, questions: [...new Set(questions)], bagConversion };
}
